name: open_port_query_firewall
label: Query NGFW for Open Ports
description: |
    Queries firewall for rules allowing traffic from a specified zone
type: panos
labels:
    collection: lib
    output_template: Report.j2

variables:
-   name: untrust_zone
    type_hint: dropdown
    description: Find ports open to this untrusted zone
    default: internet
    source: zone_names
  - name: TARGET_IP
    description: NGFW IP or Hostname
    default: 192.168.55.10
    type_hint: hidden

snippets:
-   name: Get_Policies
    cmd: show
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name="vsys1"]/rulebase/security/rules
    outputs:
    -   name: full_output
        capture_list: ./entry
    -   name: full_output_as_object
        capture_list: ./entry
        filter_items: ( item |
            difference(
            element_value("entry.from.member"),
            ["any", "{{ untrust_zone }}"]
            ) | length == 0
            ) and ( item | element_value("entry.action") == "allow" )
#        filter_items: (item | element_value("entry.from.member") in ["any", "{{ untrust_zone
#            }}"]) and (item | element_value("entry.action") == "allow")
    -   name: untrust_zone_var
        capture_variable: "{{ untrust_zone }}"
    -   name: target_var
        capture_variable: "{{ TARGET_IP }}"