# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: checking_url_category
# label used for menu selection
label: query NGFW API to get url category
description: input one or more URLs and get their respective URL categories based on PAN-DB responses
type: python3

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - PAN-OS

# ---------------------------------------------------------------------
# end of preamble section

# variables section

variables:
  - name: url_list
    description: list of URLs to ping
    default: []
    type_hint: list


# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
snippets:
  - name: url_check
    file: url_check.py
    input_type: cli

# ---------------------------------------------------------------------
# end of snippets section