name: bruteForce_exception_set
label: Add Brute Force Exceptions to vulnerability profile

description: |
  Add the recommended brute force exceptions to a named vulnerability profile
  Knowledge article: https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClmpCAC

type: template

extends:

labels:
  collection:
    - Configure
    - NGFW

variables:
  - name: profile_name
    description: Vulnerability Profile
    default: Outbound
    type_hint: text


snippets:
  - name: bruteForce_exception.conf
  - file: bruteForce_exception.conf

