name: move_rule_rest_test2
label: Move security rule test

description: |
  This skillet demonstrates a simple REST api call to move a firewall rule

type: rest

extends:

labels:
  collection:
    - Configure
    - PANOS

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: ip_address
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password
  - name: rule_name
    description: name of security rule to move
    default: rule1
    type_hint: text
  - name: ref_rule
    description: rule to move before or after
    default: rule2
    type_hint: text
  - name: where
    description: move before or after other rule
    default: before
    type_hint: dropdown
    dd_list:
      - key: after
        value: after
      - key: before
        value: before
      - key: top
        value: top
      - key: bottom
        value: bottom


snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key
  - name: move_rule
    path: https://{{ TARGET_IP }}/api/?type=config&action=move&xpath=/config/devices/entry/vsys/entry[@name='vsys1']/rulebase/security/rules/entry[@name='{{ rule_name }}']&where={{ where }}{%- if where == 'before' or where == 'after' %}&dst={{ ref_rule }}{% endif %}&key={{ api_key }}
    output_type: xml


