name: move_rule_rest_test
label: Move security rule test

description: |
  This skillet demonstrates a simple REST api call to move a firewall rule

type: rest

extends:

labels:
  collection:
    - Configure
    - PANOS

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: TARGET_IP
    description: firewall ip address
    default: 127.0.0.1
    type_hint: ip_address
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password

# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key

