name: panos-open-ports
label: Query Firewall for Open Port Rules
description: |
    For Tobi
type: panos
labels:
    collection: Open_Port_Query
    output_template: Report.j2

variables:
-   name: untrust_zone
    type_hint: text
    description: Untrust Zone
    default: internet
    help_text: ''
snippets:
-   name: Get_Policies
    cmd: show
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name="vsys1"]/rulebase/security/rules
    outputs:
    -   name: full_output_as_object
        capture_list: ./entry
        filter_items: (item | element_value("entry.from.member") in ["any", "{{ untrust_zone
            }}"]) and (item | element_value("entry.action") == "allow")
